- name : declare variable in play level
  hosts : all
  connection : local
  vars :
    URL : play.example.com
    task :
      - name : access variable
        ansible.builtin.debug:
          msg : URL == {{URL}}
