- name : declare variable in playlevel
  hosts : all
  connection : local
  vars :
    URL : play.example.com
    tasks :
      - name : access variable
        ansible.builtin.debug:
          msg : URL == {{URL}}
