- name : declare variable in playlevel
  hosts : all
  connection : local
  vars :
    URL : uma.com
    tasks :
      - name : access variable from play level
        ansible.builtin.debug:
          msg : URL == {{URL}}
