- name: Declare variable at Play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable at task level
  hosts: all
  connection: local
  tasks:
  - name: access variable from task level
    ansible.builtin.debug:
      msg: URL == {{URL}}
      vars:
      URL: play.example.com


